# Generated by Django 4.2.7 on 2025-10-19 18:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('telephone_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone 2')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('fonction', models.CharField(choices=[('Ingénieur', 'Ingénieur'), ('Chef_Chantier', 'Chef de Chantier'), ('Maçon', 'Maçon'), ('Ferrailleur', 'Ferrailleur'), ('Électricien', 'Électricien'), ('Plombier', 'Plombier'), ('Charpentier', 'Charpentier'), ('Chauffeur', 'Chauffeur'), ('Gardien', 'Gardien'), ('Autre', 'Autre')], max_length=20, verbose_name='Fonction')),
                ('type_contrat', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('Journalier', 'Journalier'), ('Prestataire', 'Prestataire')], max_length=20, verbose_name='Type de contrat')),
                ('salaire_journalier', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Salaire journalier')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_embauche', models.DateField(blank=True, null=True, verbose_name="Date d'embauche")),
                ('date_fin_contrat', models.DateField(blank=True, null=True, verbose_name='Date de fin de contrat')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='personnel/', verbose_name='Photo')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Personnel',
                'verbose_name_plural': 'Personnel',
                'ordering': ['nom', 'prenom'],
                'indexes': [models.Index(fields=['nom', 'prenom'], name='personnel_p_nom_351580_idx'), models.Index(fields=['fonction'], name='personnel_p_fonctio_729daa_idx'), models.Index(fields=['actif'], name='personnel_p_actif_df4ff4_idx')],
            },
        ),
        migrations.CreateModel(
            name='AffectationPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('role_chantier', models.CharField(choices=[('Chef', 'Chef'), ('Superviseur', 'Superviseur'), ('Ouvrier', 'Ouvrier'), ('Technicien', 'Technicien'), ('Support', 'Support')], default='Ouvrier', max_length=20, verbose_name='Rôle sur le chantier')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='personnel.personnel', verbose_name='Personnel')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_personnel', to='projects.projet', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Affectation de personnel',
                'verbose_name_plural': 'Affectations de personnel',
                'ordering': ['-date_debut'],
                'indexes': [models.Index(fields=['personnel'], name='personnel_a_personn_b38bba_idx'), models.Index(fields=['projet'], name='personnel_a_projet__2e7172_idx'), models.Index(fields=['date_debut', 'date_fin'], name='personnel_a_date_de_04b9ef_idx')],
                'unique_together': {('personnel', 'projet', 'date_debut')},
            },
        ),
    ]
