# Generated by Django 5.2.7 on 2025-10-25 13:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateField(verbose_name='Date de paiement')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Montant')),
                ('nombre_jours', models.IntegerField(blank=True, help_text='Pour les journaliers', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nombre de jours')),
                ('mode_paiement', models.CharField(choices=[('Espèces', 'Espèces'), ('Chèque', 'Chèque'), ('Virement', 'Virement'), ('Mobile_Money', 'Mobile Money')], default='Espèces', max_length=20, verbose_name='Mode de paiement')),
                ('statut', models.CharField(choices=[('Validé', 'Validé'), ('En_attente', 'En attente'), ('Rejeté', 'Rejeté')], default='En_attente', max_length=20, verbose_name='Statut')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('piece_justificative', models.FileField(blank=True, null=True, upload_to='paiements_personnel/', verbose_name='Pièce justificative')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='personnel.personnel', verbose_name='Personnel')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_personnel', to='projects.projet', verbose_name='Projet')),
                ('saisi_par', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='paiements_personnel_saisis', to=settings.AUTH_USER_MODEL, verbose_name='Saisi par')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_personnel_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Paiement de personnel',
                'verbose_name_plural': 'Paiements de personnel',
                'ordering': ['-date_paiement', '-date_creation'],
                'indexes': [models.Index(fields=['personnel'], name='personnel_p_personn_093cc9_idx'), models.Index(fields=['projet'], name='personnel_p_projet__5f7c47_idx'), models.Index(fields=['date_paiement'], name='personnel_p_date_pa_748c88_idx'), models.Index(fields=['statut'], name='personnel_p_statut_6ef437_idx')],
            },
        ),
    ]
