# Generated by Django 5.2.7 on 2025-11-03 06:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_paiementpersonnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='salaire_convenu',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Montant total convenu avec l'ouvrier pour un projet ou contrat", max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Salaire convenu'),
        ),
    ]
