# Generated by Django 4.2.7 on 2025-10-19 18:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_projet', models.CharField(help_text='Généré automatiquement', max_length=50, unique=True, verbose_name='Code projet')),
                ('nom_projet', models.CharField(max_length=255, verbose_name='Nom du projet')),
                ('montant_prevu', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant prévu')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin_prevue', models.DateField(blank=True, null=True, verbose_name='Date de fin prévue')),
                ('date_fin_reelle', models.DateField(blank=True, null=True, verbose_name='Date de fin réelle')),
                ('statut', models.CharField(choices=[('Planifié', 'Planifié'), ('En_cours', 'En cours'), ('Suspendu', 'Suspendu'), ('Terminé', 'Terminé'), ('Annulé', 'Annulé')], default='Planifié', max_length=20, verbose_name='Statut')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('adresse_chantier', models.TextField(blank=True, null=True, verbose_name='Adresse du chantier')),
                ('ville_chantier', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville du chantier')),
                ('pourcentage_avancement', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Avancement (%)')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='projets', to='clients.client', verbose_name='Client')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['code_projet'], name='projects_pr_code_pr_99e180_idx'), models.Index(fields=['statut'], name='projects_pr_statut_a235d9_idx'), models.Index(fields=['client'], name='projects_pr_client__47144e_idx'), models.Index(fields=['date_debut', 'date_fin_prevue'], name='projects_pr_date_de_237838_idx')],
            },
        ),
    ]
