# Generated by Django 5.2.7 on 2025-10-26 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(max_length=100, unique=True, verbose_name='Clé')),
                ('valeur', models.TextField(blank=True, null=True, verbose_name='Valeur')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('type_donnee', models.CharField(choices=[('Texte', 'Texte'), ('Nombre', 'Nombre'), ('Boolean', 'Boolean'), ('JSON', 'JSON')], default='Texte', max_length=20, verbose_name='Type de donnée')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Paramètre',
                'verbose_name_plural': 'Paramètres',
                'ordering': ['cle'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('Photo', 'Photo'), ('Plan', 'Plan'), ('Contrat', 'Contrat'), ('Rapport', 'Rapport'), ('Facture_Fournisseur', 'Facture Fournisseur'), ('Autre', 'Autre')], max_length=30, verbose_name='Type de document')),
                ('nom_fichier', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('fichier', models.FileField(upload_to='documents/%Y/%m/', verbose_name='Fichier')),
                ('taille_ko', models.IntegerField(blank=True, null=True, verbose_name='Taille (Ko)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_upload', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.projet', verbose_name='Projet')),
                ('upload_par', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='documents_uploades', to=settings.AUTH_USER_MODEL, verbose_name='Uploadé par')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-date_upload'],
                'indexes': [models.Index(fields=['projet'], name='core_docume_projet__855818_idx'), models.Index(fields=['type_document'], name='core_docume_type_do_20821b_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_concernee', models.CharField(max_length=50, verbose_name='Table concernée')),
                ('id_enregistrement', models.IntegerField(verbose_name='ID enregistrement')),
                ('type_action', models.CharField(choices=[('Création', 'Création'), ('Modification', 'Modification'), ('Suppression', 'Suppression')], max_length=20, verbose_name="Type d'action")),
                ('anciennes_valeurs', models.JSONField(blank=True, null=True, verbose_name='Anciennes valeurs')),
                ('nouvelles_valeurs', models.JSONField(blank=True, null=True, verbose_name='Nouvelles valeurs')),
                ('date_action', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'action")),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='modifications_effectuees', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Historique de modification',
                'verbose_name_plural': 'Historiques de modifications',
                'ordering': ['-date_action'],
                'indexes': [models.Index(fields=['table_concernee'], name='core_histor_table_c_496e44_idx'), models.Index(fields=['date_action'], name='core_histor_date_ac_22bc80_idx'), models.Index(fields=['utilisateur'], name='core_histor_utilisa_c8b233_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('type', models.CharField(choices=[('Info', 'Info'), ('Alerte', 'Alerte'), ('Erreur', 'Erreur'), ('Succès', 'Succès')], default='Info', max_length=20, verbose_name='Type')),
                ('lu', models.BooleanField(default=False, verbose_name='Lu')),
                ('lien', models.CharField(blank=True, max_length=500, null=True, verbose_name='Lien')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_lecture', models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['utilisateur'], name='core_notifi_utilisa_cf225a_idx'), models.Index(fields=['lu'], name='core_notifi_lu_898a77_idx'), models.Index(fields=['date_creation'], name='core_notifi_date_cr_73d1d1_idx')],
            },
        ),
    ]
