# Generated by Django 4.2.7 on 2025-10-19 18:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Code')),
                ('couleur_hex', models.CharField(default='#6B7280', max_length=7, verbose_name='Couleur (hex)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('ordre_affichage', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Catégorie de dépense',
                'verbose_name_plural': 'Catégories de dépenses',
                'ordering': ['ordre_affichage', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='Personne de contact')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('telephone_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone 2')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('ville', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville')),
                ('nif', models.CharField(blank=True, max_length=50, null=True, verbose_name='NIF')),
                ('type', models.CharField(choices=[('Matériaux', 'Matériaux'), ('Equipement', 'Équipement'), ('Services', 'Services'), ('Transport', 'Transport'), ('Autre', 'Autre')], default='Autre', max_length=20, verbose_name='Type')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['nom'],
                'indexes': [models.Index(fields=['nom'], name='finances_fo_nom_8dc602_idx'), models.Index(fields=['type'], name='finances_fo_type_e36853_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Dépôt', 'Dépôt'), ('Retrait', 'Retrait')], max_length=10, verbose_name='Type')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Montant')),
                ('date_transaction', models.DateField(verbose_name='Date de transaction')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence')),
                ('mode_paiement', models.CharField(choices=[('Espèces', 'Espèces'), ('Chèque', 'Chèque'), ('Virement', 'Virement'), ('Mobile_Money', 'Mobile Money')], max_length=20, verbose_name='Mode de paiement')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('piece_justificative', models.FileField(blank=True, null=True, upload_to='transactions/', verbose_name='Pièce justificative')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='projects.projet', verbose_name='Projet')),
                ('saisi_par', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transactions_saisies', to=settings.AUTH_USER_MODEL, verbose_name='Saisi par')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date_transaction', '-date_creation'],
                'indexes': [models.Index(fields=['projet'], name='finances_tr_projet__30d75c_idx'), models.Index(fields=['type'], name='finances_tr_type_db9430_idx'), models.Index(fields=['date_transaction'], name='finances_tr_date_tr_5f52e5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_depense', models.DateField(verbose_name='Date de dépense')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Montant')),
                ('mode_paiement', models.CharField(choices=[('Espèces', 'Espèces'), ('Chèque', 'Chèque'), ('Virement', 'Virement'), ('Mobile_Money', 'Mobile Money')], max_length=20, verbose_name='Mode de paiement')),
                ('numero_facture', models.CharField(blank=True, max_length=100, null=True, verbose_name='N° facture')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('piece_justificative', models.FileField(blank=True, null=True, upload_to='depenses/', verbose_name='Pièce justificative')),
                ('statut', models.CharField(choices=[('Validée', 'Validée'), ('En_attente', 'En attente'), ('Rejetée', 'Rejetée')], default='En_attente', max_length=20, verbose_name='Statut')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='depenses', to='finances.categoriedepense', verbose_name='Catégorie')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses', to='finances.fournisseur', verbose_name='Fournisseur')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='projects.projet', verbose_name='Projet')),
                ('saisi_par', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='depenses_saisies', to=settings.AUTH_USER_MODEL, verbose_name='Saisi par')),
                ('validee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validée par')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date_depense', '-date_creation'],
                'indexes': [models.Index(fields=['projet'], name='finances_de_projet__2375fb_idx'), models.Index(fields=['categorie'], name='finances_de_categor_388c96_idx'), models.Index(fields=['date_depense'], name='finances_de_date_de_40a12f_idx'), models.Index(fields=['statut'], name='finances_de_statut_1d2bdb_idx')],
            },
        ),
    ]
