# Generated by Django 5.2.7 on 2025-10-28 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='categorie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='statut',
            field=models.CharField(default='Validée', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('Espèces', 'Espèces'), ('Chèque', 'Chèque'), ('Virement', 'Virement'), ('Mobile_Money', 'Mobile Money')], max_length=20, null=True, verbose_name='Mode de paiement'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='saisi_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='transactions_saisies', to=settings.AUTH_USER_MODEL, verbose_name='Saisi par'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Dépôt', 'Dépôt'), ('Retrait', 'Retrait'), ('Dépense', 'Dépense')], max_length=10, verbose_name='Type'),
        ),
    ]
