# Generated by Django 4.2.7 on 2025-10-19 18:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_devis', models.CharField(help_text='Généré automatiquement', max_length=50, unique=True, verbose_name='N° devis')),
                ('date_emission', models.DateField(verbose_name="Date d'émission")),
                ('date_validite', models.DateField(verbose_name='Date de validité')),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Montant HT')),
                ('taux_tva', models.DecimalField(decimal_places=2, default=18.0, max_digits=5, verbose_name='Taux TVA (%)')),
                ('statut', models.CharField(choices=[('Brouillon', 'Brouillon'), ('Envoyé', 'Envoyé'), ('Accepté', 'Accepté'), ('Refusé', 'Refusé'), ('Expiré', 'Expiré')], default='Brouillon', max_length=20, verbose_name='Statut')),
                ('conditions_paiement', models.TextField(blank=True, null=True, verbose_name='Conditions de paiement')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='devis', to='clients.client', verbose_name='Client')),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='devis_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis', to='projects.projet', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
                'ordering': ['-date_emission', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(help_text='Généré automatiquement', max_length=50, unique=True, verbose_name='N° facture')),
                ('date_emission', models.DateField(verbose_name="Date d'émission")),
                ('date_echeance', models.DateField(verbose_name="Date d'échéance")),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Montant HT')),
                ('taux_tva', models.DecimalField(decimal_places=2, default=18.0, max_digits=5, verbose_name='Taux TVA (%)')),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant payé')),
                ('statut_paiement', models.CharField(choices=[('Impayée', 'Impayée'), ('Partielle', 'Partielle'), ('Payée', 'Payée'), ('En_retard', 'En retard')], default='Impayée', max_length=20, verbose_name='Statut de paiement')),
                ('conditions_paiement', models.TextField(blank=True, null=True, verbose_name='Conditions de paiement')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='factures', to='clients.client', verbose_name='Client')),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='factures_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('devis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='invoicing.devis', verbose_name='Devis')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='projects.projet', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-date_emission', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.IntegerField(default=1, verbose_name='Ordre')),
                ('designation', models.CharField(max_length=255, verbose_name='Désignation')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('quantite', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Quantité')),
                ('unite', models.CharField(default='Forfait', max_length=20, verbose_name='Unité')),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix unitaire HT')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='invoicing.facture', verbose_name='Facture')),
            ],
            options={
                'verbose_name': 'Ligne de facture',
                'verbose_name_plural': 'Lignes de factures',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='LigneDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.IntegerField(default=1, verbose_name='Ordre')),
                ('designation', models.CharField(max_length=255, verbose_name='Désignation')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('quantite', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Quantité')),
                ('unite', models.CharField(default='Forfait', max_length=20, verbose_name='Unité')),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix unitaire HT')),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='invoicing.devis', verbose_name='Devis')),
            ],
            options={
                'verbose_name': 'Ligne de devis',
                'verbose_name_plural': 'Lignes de devis',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='PaiementFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateField(verbose_name='Date de paiement')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Montant')),
                ('mode_paiement', models.CharField(choices=[('Espèces', 'Espèces'), ('Chèque', 'Chèque'), ('Virement', 'Virement'), ('Mobile_Money', 'Mobile Money')], max_length=20, verbose_name='Mode de paiement')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('enregistre_par', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='paiements_enregistres', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='invoicing.facture', verbose_name='Facture')),
            ],
            options={
                'verbose_name': 'Paiement de facture',
                'verbose_name_plural': 'Paiements de factures',
                'ordering': ['-date_paiement', '-date_creation'],
                'indexes': [models.Index(fields=['facture'], name='invoicing_p_facture_d80298_idx'), models.Index(fields=['date_paiement'], name='invoicing_p_date_pa_02eecd_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['numero_facture'], name='invoicing_f_numero__f26fe0_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['client'], name='invoicing_f_client__d23d2b_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['statut_paiement'], name='invoicing_f_statut__c3a40b_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['date_emission'], name='invoicing_f_date_em_d402a2_idx'),
        ),
        migrations.AddIndex(
            model_name='devis',
            index=models.Index(fields=['numero_devis'], name='invoicing_d_numero__5a9c04_idx'),
        ),
        migrations.AddIndex(
            model_name='devis',
            index=models.Index(fields=['client'], name='invoicing_d_client__5be93c_idx'),
        ),
        migrations.AddIndex(
            model_name='devis',
            index=models.Index(fields=['statut'], name='invoicing_d_statut_da3314_idx'),
        ),
        migrations.AddIndex(
            model_name='devis',
            index=models.Index(fields=['date_emission'], name='invoicing_d_date_em_a492e0_idx'),
        ),
    ]
