# Generated by Django 5.2.7 on 2025-11-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='appliquer_tva',
            field=models.BooleanField(default=True, verbose_name='Appliquer la TVA'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='statut',
            field=models.CharField(choices=[('Brouillon', 'Brouillon'), ('Envoyé', 'Envoyé'), ('Accepté', 'Accepté'), ('Refusé', 'Refusé'), ('Expiré', 'Expiré'), ('Gagné', 'Gagné'), ('Perdu', 'Perdu')], default='Brouillon', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='taux_tva',
            field=models.DecimalField(blank=True, decimal_places=2, default=18.0, max_digits=5, null=True, verbose_name='Taux TVA (%)'),
        ),
    ]
