# Generated by Django 4.2.7 on 2025-10-19 18:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_tache', models.CharField(max_length=255, verbose_name='Nom de la tâche')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin_prevue', models.DateField(verbose_name='Date de fin prévue')),
                ('date_fin_reelle', models.DateField(blank=True, null=True, verbose_name='Date de fin réelle')),
                ('priorite', models.CharField(choices=[('Basse', 'Basse'), ('Moyenne', 'Moyenne'), ('Haute', 'Haute'), ('Critique', 'Critique')], default='Moyenne', max_length=20, verbose_name='Priorité')),
                ('statut', models.CharField(choices=[('A_faire', 'À faire'), ('En_cours', 'En cours'), ('En_pause', 'En pause'), ('Terminée', 'Terminée'), ('Bloquée', 'Bloquée'), ('Annulée', 'Annulée')], default='A_faire', max_length=20, verbose_name='Statut')),
                ('pourcentage_progression', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Progression (%)')),
                ('ordre_affichage', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='projects.projet', verbose_name='Projet')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_responsable', to='personnel.personnel', verbose_name='Responsable')),
                ('tache_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_taches', to='planning.tache', verbose_name='Tâche parente')),
            ],
            options={
                'verbose_name': 'Tâche',
                'verbose_name_plural': 'Tâches',
                'ordering': ['ordre_affichage', 'date_debut'],
                'indexes': [models.Index(fields=['projet'], name='planning_ta_projet__38b6c8_idx'), models.Index(fields=['statut'], name='planning_ta_statut_c5a87b_idx'), models.Index(fields=['date_debut', 'date_fin_prevue'], name='planning_ta_date_de_887b5e_idx'), models.Index(fields=['responsable'], name='planning_ta_respons_cd12b4_idx')],
            },
        ),
    ]
