# Generated by Django 4.2.7 on 2025-10-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('entreprise', models.CharField(blank=True, max_length=200, null=True, verbose_name='Entreprise')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('telephone_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone 2')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('ville', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville')),
                ('pays', models.CharField(default='Guinée', max_length=100, verbose_name='Pays')),
                ('nif', models.CharField(blank=True, max_length=50, null=True, verbose_name='NIF')),
                ('rccm', models.CharField(blank=True, max_length=50, null=True, verbose_name='RCCM')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['nom_complet'],
                'indexes': [models.Index(fields=['nom_complet'], name='clients_cli_nom_com_04f1dd_idx'), models.Index(fields=['entreprise'], name='clients_cli_entrepr_cbe1bd_idx'), models.Index(fields=['email'], name='clients_cli_email_56b9fc_idx')],
            },
        ),
    ]
